arch:
  - amd64
  - ppc64le

language: go
sudo: false
go:
  - 1.18.x
  - 1.19.x
  - 1.20.x
  - tip
matrix:
  allow_failures:
  - go: tip
install:
  - go get -t -v ./...
script:
  - go test -v ./...
  - ./compileall.sh
