language: go
sudo: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip
matrix:
  allow_failures:
  - go: tip
install:
  - go get -t -v ./...
script:
  - go test -v ./...
  - ./compileall.sh
